; Generated by Coffee-AHK/0.0.17
global __ci_z__ := Func("z_53")
global $ := {}
$.beep := Func("z_52")
$.blockInput := Func("z_51")
$.click := Func("z_50")
global __index_debounce__ := 0
global __timer_debounce__ := {}
$.debounce := Func("z_49")
$.delay := Func("z_47")
$.exit := Func("z_46")
$.findColor := Func("z_45")
$.findImage := Func("z_44")
$.formatHotkey := Func("z_43")
$.getColor := Func("z_42")
$.getPosition := Func("z_41")
$.getState := Func("z_40")
$.i := Func("z_39")
$.includes := Func("z_38")
$.info := Func("z_37")
$.length := Func("z_36")
$.move := Func("z_35")
$.now := Func("z_34")
$.off := Func("z_33")
$.on := Func("z_32")
$.open := Func("z_31")
$.play := Func("z_30")
$.press := Func("z_29")
$.push := Func("z_28")
$.random := Func("z_27")
$.reload := Func("z_26")
$.replace := Func("z_25")
$.reverse := Func("z_24")
$.setFixed := Func("z_23")
$.sleep := Func("z_22")
$.split := Func("z_21")
$.suspend := Func("z_20")
global __index_throttle__ := 0
global __timer_throttle__ := {}
global __ts_throttle__ := {}
$.throttle := Func("z_19")
$.toLowerCase := Func("z_16")
$.toString := Func("z_15")
$.toUpperCase := Func("z_14")
$.trim := Func("z_13")
$.trimEnd := Func("z_12")
$.trimStart := Func("z_11")
$.type := Func("z_10")
global alert := Func("z_9")
global clearInterval := Func("z_8")
global clearTimeout := Func("z_7")
global Math := {abs: Func("z_6"), ceil: Func("z_5"), floor: Func("z_4"), round: Func("z_3")}
global setInterval := Func("z_2")
global setTimeout := Func("z_1")
alert.Call($.reverse.Call([1, 2, 3]))
z_1(callback, time) {
  if (($.type.Call(callback)) == "function") {
    callback := callback.Bind()
  }
  __type__ := $.type.Call(time)
  if !(__type__ == "number") {
    throw Exception("setTimeout: invalid time type '" . (__type__) . "'")
  }
  if (time <= 0) {
    time := 1
  }
  SetTimer, % callback, % 0 - time
  return callback
}
z_2(callback, time) {
  if (($.type.Call(callback)) == "function") {
    callback := callback.Bind()
  }
  __type__ := $.type.Call(time)
  if !(__type__ == "number") {
    throw Exception("setTimeout: invalid time type '" . (__type__) . "'")
  }
  if !(time > 0) {
    throw Exception("setTimeout: invalid time value '" . (time) . "'")
  }
  SetTimer, % callback, % time
  return callback
}
z_3(n) {
  return Round(n)
}
z_4(n) {
  return Floor(n)
}
z_5(n) {
  return Ceil(n)
}
z_6(n) {
  return Abs(n)
}
z_7(callback) {
  if !(callback) {
    return
  }
  SetTimer, % callback, Delete
}
z_8(callback) {
  if !(callback) {
    return
  }
  SetTimer, % callback, Delete
}
z_9(message := "") {
  __msg__ := $.toString.Call(message)
  MsgBox, % __msg__
}
z_10(input) {
  if input is Number
    return "number"
  if (IsFunc(input)) {
    return "function"
  }
  if (IsObject(input)) {
    if (input.Count() == input.Length()) {
      return "array"
    }
    return "object"
  }
  return "string"
}
z_11(input, omitting := " `t") {
  return LTrim(input, omitting)
}
z_12(input, omitting := " `t") {
  return RTrim(input, omitting)
}
z_13(input, omitting := " `t") {
  return Trim(input, omitting)
}
z_14(input) {
  StringUpper, __result__, input
  return __result__
}
z_15(input) {
  __type__ := $.type.Call(input)
  if (__type__ == "array") {
    __result__ := ""
    for __index_for__, key in input {
      __result__ := "" . (__result__) . ", " . ($.toString.Call(key)) . ""
    }
    return "[" . ($.trim.Call(__result__, " ,")) . "]"
  } else if (__type__ == "object") {
    __result__ := ""
    for key, value in input {
      __result__ := "" . (__result__) . ", " . (key) . ": " . ($.toString.Call(value)) . ""
    }
    return "{" . ($.trim.Call(__result__, " ,")) . "}"
  }
  return input
}
z_16(input) {
  StringLower, __result__, input
  return __result__
}
z_17(index, callback) {
  callback.Call()
  __ts_throttle__[__ci_z__.Call(index)] := $.now.Call()
}
z_18(index, time, callback) {
  clearTimeout.Call(__timer_throttle__[__ci_z__.Call(index)])
  __timer_throttle__[__ci_z__.Call(index)] := setTimeout.Call(Func("z_17").Bind(index, callback), __ts_throttle__[__ci_z__.Call(index)] - $.now.Call() + time)
}
z_19(time, callback) {
  __index_throttle__++
  __ts_throttle__[__ci_z__.Call(__index_throttle__)] := 0
  return Func("z_18").Bind(__index_throttle__, time, callback)
}
z_20(isSuspended := "Toggle") {
  if (isSuspended != "Toggle") {
    if (isSuspended) {
      isSuspended := "On"
    } else {
      isSuspended := "Off"
    }
  }
  Suspend, % isSuspended
}
z_21(input, delimiter) {
  return StrSplit(input, delimiter)
}
z_22(time) {
  Sleep, % time
}
z_23(isFixed := "Toggle") {
  if (isFixed != "Toggle") {
    if (isFixed) {
      isFixed := "On"
    } else {
      isFixed := "Off"
    }
  }
  Winset AlwaysOnTop, % isFixed, A
}
z_24(input) {
  __type__ := $.type.Call(input)
  if !(__type__ == "array") {
    throw Exception("$.reverse: invalid type '" . (__type__) . "'")
  }
  __len__ := $.length.Call(input)
  __output__ := []
  for i, key in input {
    i := i - 1
    __output__[__ci_z__.Call(__len__ - 1 - i)] := key
  }
  return __output__
}
z_25(input, searchment, replacement, limit := -1) {
  return StrReplace(input, searchment, replacement, limit)
}
z_26() {
  Reload
}
z_27(min := 0, max := 1) {
  Random, __result__, min, max
  return __result__
}
z_28(list, item) {
  list.Push(item)
  return list
}
z_29(listInput*) {
  if !($.length.Call(listInput)) {
    throw Exception("$.press: invalid key")
  }
  __listKey__ := []
  for __index_for__, input in listInput {
    __input__ := $.toLowerCase.Call(input)
    __input__ := $.replace.Call(__input__, " ", "")
    __input__ := $.replace.Call(__input__, "-", "")
    __list__ := $.split.Call(__input__, "+")
    for __index_for__, it in __list__ {
      __listKey__.Push(it)
    }
  }
  __listResult__ := []
  __len__ := $.length.Call(__listKey__)
  for i, key in __listKey__ {
    i := i - 1
    if (i == __len__ - 1) {
      __listResult__[__ci_z__.Call(i)] := $.split.Call(key, ":")
      continue
    }
    if ($.includes.Call(key, ":")) {
      __listResult__[__ci_z__.Call(i)] := $.split.Call(key, ":")
      __listResult__[__ci_z__.Call((__len__ - 1) * 2 - i)] := $.split.Call(key, ":")
    } else {
      __listResult__[__ci_z__.Call(i)] := [key, "down"]
      __listResult__[__ci_z__.Call((__len__ - 1) * 2 - i)] := [key, "up"]
    }
  }
  for i, it in __listResult__ {
    i := i - 1
    if (it[1] == "win") {
      it[1] := "lwin"
    }
    __listResult__[__ci_z__.Call(i)] := $.trim.Call("" . (it[1]) . " " . (it[2]) . "")
  }
  __output__ := ""
  for __index_for__, it in __listResult__ {
    __output__ := "" . (__output__) . "{" . (it) . "}"
  }
  Send, % __output__
}
z_30(filename) {
  SoundPlay, % filename
}
z_31(source) {
  Run, % source
}
z_32(key, callback) {
  key := $.formatHotkey.Call(key)
  Hotkey, % key, % callback, On
}
z_33(key, callback) {
  key := $.formatHotkey.Call(key)
  Hotkey, % key, % callback, Off
}
z_34() {
  return A_TickCount
}
z_35(point := "", speed := 0) {
  if !(point) {
    throw Exception("$.move: invalid point")
  }
  MouseMove, point[1], point[2], speed
}
z_36(input) {
  __type__ := $.type.Call(input)
  switch __type__ {
    case "array": {
      return input.Length()
    }
    case "object": {
      return input.Count()
    }
    case "string": {
      return StrLen(input)
    }
    default: {
      throw Exception("$.length: invalid type '" . (__type__) . "'")
    }
  }
}
z_37(message, point := "") {
  if !(message) {
    return message
  }
  if !(point) {
    point := $.getPosition.Call()
  }
  __msg__ := $.toString.Call(message)
  ToolTip, % __msg__, % point[1], % point[2]
  return message
}
z_38(input, needle) {
  __type__ := $.type.Call(input)
  if (__type__ == "string" || __type__ == "number") {
    return (InStr(input, needle)) > 0
  }
  if (__type__ == "array") {
    for __index_for__, it in input {
      if (it == needle) {
        return true
      }
    }
    return false
  }
  throw Exception("$.includes: invalid type '" . (__type__) . "'")
}
z_39(message) {
  $.info.Call("" . ($.now.Call()) . " " . ($.toString.Call(message)) . "")
  return message
}
z_40(key) {
  return GetKeyState(key, "P")
}
z_41() {
  MouseGetPos, __x__, __y__
  return [__x__, __y__]
}
z_42(point := "") {
  if !(point) {
    point := $.getPosition.Call()
  }
  PixelGetColor, __result__, % point[1], % point[2], RGB
  return __result__
}
z_43(key) {
  __listkey__ := []
  __key__ := $.toLowerCase.Call(key)
  __key__ := $.replace.Call(__key__, " ", "")
  __key__ := $.replace.Call(__key__, "-", "")
  _list := $.split.Call(__key__, "+")
  for __index_for__, it in _list {
    __listkey__.Push(it)
  }
  __isAlt__ := false
  __isCtrl__ := false
  __isShift__ := false
  __isWin__ := false
  __listResult__ := []
  for __index_for__, key in __listkey__ {
    if (key == "alt") {
      __isAlt__ := true
      continue
    }
    if (key == "ctrl") {
      __isCtrl__ := true
      continue
    }
    if (key == "shift") {
      __isShift__ := true
      continue
    }
    if (key == "win") {
      __isWin__ := true
      continue
    }
    __listResult__.Push(key)
  }
  __prefix__ := ""
  if (__isAlt__) {
    __prefix__ := "" . (__prefix__) . "!"
  }
  if (__isCtrl__) {
    __prefix__ := "" . (__prefix__) . "^"
  }
  if (__isShift__) {
    __prefix__ := "" . (__prefix__) . "+"
  }
  if (__isWin__) {
    __prefix__ := "" . (__prefix__) . "#"
  }
  __result__ := ""
  for __index_for__, it in __listResult__ {
    __result__ := "" . (__result__) . " & " . (it) . ""
  }
  return $.replace.Call("" . (__prefix__) . "" . ($.trim.Call(__result__, " &")) . "", ":", " ")
}
z_44(source, start := "", end := "") {
  if !(start) {
    start := [0, 0]
  }
  if !(end) {
    end := [A_ScreenWidth, A_ScreenHeight]
  }
  ImageSearch __x__, __y__, start[1], start[2], end[1], end[2], % A_ScriptDir . "\\\" . source
  return [__x__, __y__]
}
z_45(color, start := "", end := "", variation := 0) {
  if !(start) {
    start := [0, 0]
  }
  if !(end) {
    end := [A_ScreenWidth, A_ScreenHeight]
  }
  PixelSearch __x__, __y__, start[1], start[2], end[1], end[2], color, variation, Fast RGB
  return [__x__, __y__]
}
z_46() {
  ExitApp
}
z_47(time, callback) {
  __timer__ := setTimeout.Call(callback, time)
  return __timer__
}
z_48(index, time, callback) {
  clearTimeout.Call(__timer_debounce__[__ci_z__.Call(index)])
  __timer_debounce__[__ci_z__.Call(index)] := setTimeout.Call(callback, time)
}
z_49(time, callback) {
  __index_debounce__++
  return Func("z_48").Bind(__index_debounce__, time, callback)
}
z_50(key := "left") {
  key := $.replace.Call(key, "-", "")
  key := $.replace.Call(key, ":", " ")
  Click, % key
}
z_51(block) {
  if (block) {
    BlockInput, On
    return
  }
  BlockInput, Off
}
z_52() {
  SoundBeep
}
z_53(input) {
  if input is Number
    return input + 1
  return input
}
